option(LATTICE_ASAN "Enable AddressSanitizer" OFF)
option(LATTICE_UBSAN "Enable UndefinedBehaviorSanitizer" OFF)
option(LATTICE_TSAN "Enable ThreadSanitizer" OFF)

function(lattice_apply_sanitizers target)
  if(MSVC)
    return()
  endif()
  set(_sanitizers "")
  if(LATTICE_ASAN)
    list(APPEND _sanitizers address)
  endif()
  if(LATTICE_UBSAN)
    list(APPEND _sanitizers undefined)
  endif()
  if(LATTICE_TSAN)
    list(APPEND _sanitizers thread)
  endif()
  if(_sanitizers)
    list(JOIN _sanitizers "," _san_string)
    target_compile_options(${target} PRIVATE -fsanitize=${_san_string} -fno-omit-frame-pointer)
    target_link_options(${target} PRIVATE -fsanitize=${_san_string})
  endif()
endfunction()
